updated startup

diff --git a/startup b/startup
--- a/startup
+++ b/startup
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# If you are looking for docs on this script, consult https://github.com/jshook/simple-startup
+# or, preferably, just run ./startup
+
 # functions
 containsElement () {
   local e
@@ -14,120 +17,143 @@ MAIN_SCRIPT_BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 MAIN_SCRIPT="${MAIN_SCRIPT_BASEDIR}/"$( basename $0 )
 EXECUTION_DIR=$(dirname ${MAIN_SCRIPT})
 
+
 # locate .startup directory
-SUB_COMPONENTS_DIRNAME=$( dirname $MAIN_SCRIPT_BASEDIR )"/.startup"
-SELF_COMPONENTS_DIRNAME=$( dirname $MAIN_SCRIPT)"/.startup"
-
 MAIN_SCRIPT_DIRNAME=$(dirname $MAIN_SCRIPT)
-
 if [ "${MAIN_SCRIPT_DIRNAME}" = ".startup" ]
 then export COMPONENTS_DIRNAME="${MAIN_SCRIPT_DIRNAME}"
 else export COMPONENTS_DIRNAME="${MAIN_SCRIPT_DIRNAME}/.startup"
 fi
 
-if [ ! -d "${COMPONENTS_DIRNAME}" ]
+# sanity check for only one startup script
+if [ -f "${COMPONENTS_DIRNAME}/startup" -a -f "${COMPONENTS_DIRNAME}/../startup" ]
 then
- printf "component scripts directory '${COMPONENTS_DIRNAME}' does not exist.\n"
+ printf "ERROR: You must choose where to put your one and only 'startup' script.\n"
+ printf "You have one in both locations below:\n%s\n%s\n" "${COMPONENTS_DIRNAME}/startup" "${COMPONENTS_DIRNAME}/../startup"
  exit 2
 fi
 
-# get list of components
+if [ ! -d "${COMPONENTS_DIRNAME}" ]
+then
+ printf "ERROR: component scripts directory '${COMPONENTS_DIRNAME}' does not exist.\n"
+ exit 2
+fi
 
-COMPONENT_NAMES=$(cd $COMPONENTS_DIRNAME; /bin/ls | grep -v 'startup.order' | grep -v '^startup$')
+##
+## Initialize known component scripts array
+##
 component_scriptnames_ary=()
-while read -r line; do component_scriptnames_ary+=("$line"); done <<< "${COMPONENT_NAMES}"
 
-# if startup.order is used, cross-check contents
-# not including 'startup' and 'startup.order' files
+SCRIPT_DATA=$(cd $COMPONENTS_DIRNAME; /bin/ls)
+while read -r line
+do
+ if [ "$line" = "startup.order" ] ; then continue ; fi
+ if [ "$line" = "startup" ] ; then continue ; fi
+ if [ -z "$line" ] ; then continue; fi
+ component_scriptnames_ary+=("$line")
+done <<< "$SCRIPT_DATA"
+#printf "DEBUG: component_scriptname: %s\n" "${component_scriptnames_ary[@]}" 1>&2
 
-ORDER_FILE="${COMPONENTS_DIRNAME}/startup.order"
+##
+## Initialize ordered components array
+##
+component_order_ary=()
+
+export ORDER_FILE="${COMPONENTS_DIRNAME}/startup.order"
 if [ -f "${ORDER_FILE}" ]
 then
- export COMPONENT_ORDER=$(cat ${ORDER_FILE})
-
- # verify every file listed in components exists in
- # executable script form in the .startup directory
-
- for component_name in $COMPONENT_ORDER
- do
-  COMPONENT_SCRIPT="${COMPONENTS_DIRNAME}/${component_name}"
-  if [ ! -f "${COMPONENT_SCRIPT}" ]
-  then
-   printf "component startup script '${COMPONENT_SCRIPT}' is missing, but it was listed in startup.order.\n";
-   exit 2
-  fi
-  if [ ! -x "${COMPONENT_SCRIPT}" ]
-  then
-   printf "component startup script '${COMPONENT_SCRIPT}' is not executable.\n";
-   exit 2
-  fi
- done
-
- # verify that all named components found in script form
- # exist in the startup.order file
-
- component_order_ary=()
+ # printf "DEBUG: loading order file: %s\n" "${ORDER_FILE}" 1>&2
+ ORDER_DATA=$(cat ${ORDER_FILE})
  while read -r line
  do
   if [ "$line" = "startup.order" ] ; then continue ; fi
   if [ "$line" = "startup" ] ; then continue ; fi
   component_order_ary+=("$line")
- done <<< "${COMPONENT_ORDER}"
+  COMPONENT_SCRIPT="${COMPONENTS_DIRNAME}/$line"
+  if [ ! -x "${COMPONENT_SCRIPT}" ]
+  then
+   printf "ERROR: component startup script '${COMPONENT_SCRIPT}' is not executable or it is missing.\n";
+   printf "ERROR: (it was referenced in the startup.order file in ${COMPONENTS_DIRNAME} )\n";
+   exit 2
+  fi
+ done <<< "${ORDER_DATA}"
 
+  # verify that all named components found in script form
+  # exist in the startup.order file
  for component_scriptname in "${component_scriptnames_ary[@]}"
  do
 #  printf "checking %s for ordering membership.\n" "$component_scriptname" 1>&2
   if ! containsElement "${component_scriptname}" "${component_order_ary[@]}"
   then
-   printf "There is a startup.order file, but script '${component_scriptname}' is not listed in it.\n"
+   printf "ERROR: There is a startup.order file, but script '${component_scriptname}' is not listed in it.\n"
    exit 2
   fi
  done
 else
- export COMPONENT_ORDER="$COMPONENT_NAMES"
+ component_order_ary=("${component_scriptnames_ary[@]}")
 fi
+#printf "DEBUG: component_order: %s\n" "${component_order_ary[@]}" 1>&2
 
-if [ -z "${COMPONENT_ORDER}" ]
+# warn if no component scripts found
+if [ "${#component_order_ary[@]}" -eq 0 ]
 then
- printf "There are no component scripts in ${COMPONENTS_DIRNAME}\n";
+ printf "ERROR: There are no component scripts in ${COMPONENTS_DIRNAME}\n";
  exit 2
 fi
 
 if [ ! -f "${ORDER_FILE}" ]
 then
- printf "# Component order is based on filenames.\n# Consider adding a startup.order file to control order of startup.\n" 1>&2
+ printf "# WARNING: Component order is based on filenames.\n" 1>&2
+ printf "# WARNING: Consider adding a startup.order file to control order of startup.\n" 1>&2
 fi
 
-# if no components selected, show options and help
-if [ -z "$*" ]
+##
+## Initialized selected components array
+##
+selected_components_ary=()
+# printf "DEBUG: arg:[%s]\n" $* 1>&2
+if [ "all" = "$1" ]
 then
- printf "You must select from the following available components:\n%s\n" "${COMPONENT_ORDER}"
+ printf "# INFO: selecting all components\n"; 1>&2
+ selected_components_ary=("${component_order_ary[@]}")
+elif [ ! -z "$1" ]
+then
+ printf "# INFO: selecting specific components: 1=[$1] $*\n"; 1>&2
+ selected_components_ary=( "$@" )
+ #do selected_components_ary+=("$line")
+else
+ printf "INFO: You must select from the following available components:\n" 1>&2
+ printf "%s\n" "${component_order_ary[@]}"
  exit 0
 fi
+# printf "DEBUG: selected_component: %s\n" "${selected_components_ary[@]}" 1>&2
 
-# if all is selected, change arguments to match as if they were listed out individually
-if [ "$1" = "all" ]
-then TO_RUN="${COMPONENT_ORDER}"
-else TO_RUN="$*"
-fi
-
-to_run_ary=()
-while read -r line; do to_run_ary+=("$line"); done <<< "${TO_RUN}"
-order_ary=()
-while read -r line; do order_ary+=("$line"); done <<< "${COMPONENT_ORDER}"
+ordered_components_ary=()
+for component in "${component_order_ary[@]}"
+do
+ if containsElement "${component}" "${selected_components_ary[@]}"
+ then ordered_components_ary+=("${component}")
+ else
+  printf "# INFO: component '%s' is being skipped\n" "${component}" 1>&2
+ fi
+done
+# printf "ordered_components_ary: %s\n" "${ordered_components_ary[@]}" 1>&2
 
 # execute components in order
-for selected in "${to_run_ary[@]}"
+for selected in "${ordered_components_ary[@]}"
 do
- if containsElement "${selected}" "${order_ary[@]}"
+ if containsElement "${selected}" "${component_order_ary[@]}"
  then
   FULL_SCRIPT_PATH="${COMPONENTS_DIRNAME}/${selected}"
-  printf "executing: %s\n" "${FULL_SCRIPT_PATH}" 1>&2
-  ( cd ${EXECUTION_DIR} && bash ${FULL_SCRIPT_PATH})
+  printf "INFO: executing: %s\n" "${selected}"
+  ( cd ${EXECUTIOND_DIR} && bash ${FULL_SCRIPT_PATH})
   last_status=$?
   if [[ last_status -ne 0 ]]
   then
-   printf "script %s failed with status: %s\n" "${FULL_SCRIPT_PATH}" "${last_status}"
+   printf "ERROR: script %s failed with status: %s\n" "${FULL_SCRIPT_PATH}" "${last_status}"
   fi
+ else
+  printf "ERROR component '%s'  was not found in ${COMPONENTS_DIRNAME}\n" "${selected}"
+  exit 2;
  fi
 done
