AOS and notebook import

diff --git a/startup b/startup
--- a/startup
+++ b/startup
@@ -69,7 +69,9 @@ then
  do
   if [ "$line" = "startup.order" ] ; then continue ; fi
   if [ "$line" = "startup" ] ; then continue ; fi
+#  if [ "${line:0:1}" = "3" ] ; then line= ${line#\#}; fi
   component_order_ary+=("$line")
+  line=${line#\#}
   COMPONENT_SCRIPT="${COMPONENTS_DIRNAME}/$line"
   if [ ! -x "${COMPONENT_SCRIPT}" ]
   then
@@ -84,7 +86,7 @@ then
  for component_scriptname in "${component_scriptnames_ary[@]}"
  do
 #  printf "checking %s for ordering membership.\n" "$component_scriptname" 1>&2
-  if ! containsElement "${component_scriptname}" "${component_order_ary[@]}"
+  if ! containsElement "${component_scriptname}" "${component_order_ary[@]}" && ! containsElement "#${component_scriptname}" "${component_order_ary[@]}"
   then
    printf "ERROR: There is a startup.order file, but script '${component_scriptname}' is not listed in it.\n"
    exit 2
@@ -98,7 +100,7 @@ fi
 # warn if no component scripts found
 if [ "${#component_order_ary[@]}" -eq 0 ]
 then
- printf "ERROR: There are no component scripts in ${COMPONENTS_DIRNAME}\n";
+ printf "ERROR: There are no executable scripts in ${COMPONENTS_DIRNAME}\n";
  exit 2
 fi
 
@@ -127,11 +129,11 @@ else
  printf "%s\n" "${component_order_ary[@]}"
  exit 0
 fi
-# printf "DEBUG: selected_component: %s\n" "${selected_components_ary[@]}" 1>&2
+#printf "DEBUG: selected_component: %s\n" "${selected_components_ary[@]}" 1>&2
 
 for selected in "${selected_components_ary[@]}"
 do
- if ! containsElement "${selected}" "${component_order_ary[@]}"
+ if ! containsElement "${selected}" "${component_order_ary[@]}" && ! containsElement "#${selected}" "${component_order_ary[@]}"
  then
   printf "%s was specified, but no such component could be found.\n" "${selected}"
   exit 2
@@ -141,18 +143,21 @@ done
 ordered_components_ary=()
 for component in "${component_order_ary[@]}"
 do
+ component=${component#\#}
  if containsElement "${component}" "${selected_components_ary[@]}"
  then ordered_components_ary+=("${component}")
  else
   printf "# INFO: component '%s' is being skipped\n" "${component}" 1>&2
  fi
 done
-# printf "ordered_components_ary: %s\n" "${ordered_components_ary[@]}" 1>&2
+
+#printf "component_order_ary: %s\n" "${component_order_ary[@]}" 1>&2
+#printf "ordered_components_ary: %s\n" "${ordered_components_ary[@]}" 1>&2
 
 # execute components in order
 for selected in "${ordered_components_ary[@]}"
 do
- if containsElement "${selected}" "${component_order_ary[@]}"
+ if containsElement "${selected}" "${component_order_ary[@]}" || containsElement "#${selected}" "${component_order_ary[@]}"
  then
   FULL_SCRIPT_PATH="${COMPONENTS_DIRNAME}/${selected}"
   printf "# INFO: executing: %s\n" "${selected}"
@@ -172,3 +177,4 @@ do
   exit 2;
  fi
 done
+
